#!/usr/bin/env bash

#
# Script for the final cleanup of the image (runs inside the image chroot):
# everything that must be created again on the first boot is removed.
# The cloud-init seed on /boot/firmware stays.
#
# Part of the ROS 2 port of Clover (https://github.com/CopterExpress/clover).
#
# Distributed under MIT License (available at https://opensource.org/licenses/MIT).
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/common.sh
source "${SCRIPT_DIR}/scripts/common.sh"

main() {
  require_chroot

  echo_stamp "Clean apt"
  apt-get clean -qq
  rm -rf /var/lib/apt/lists/*

  echo_stamp "Remove host keys (regenerated by cloud-init), machine-id, cloud-init state, logs, caches"
  rm -f /etc/ssh/ssh_host_*
  : > /etc/machine-id
  rm -rf /var/lib/cloud/instances /var/lib/cloud/instance /var/lib/cloud/data/*
  rm -f /var/log/cloud-init.log /var/log/cloud-init-output.log
  find /var/log -type f \( -name '*.log' -o -name '*.gz' -o -name '*.[0-9]' \) -delete
  rm -rf /var/log/journal/*
  rm -rf /root/.cache /root/.ros /root/.bash_history /home/pi/.cache /home/pi/.bash_history
  rm -rf /home/pi/ros2_ws/log
  rm -rf /tmp/* /var/tmp/*

  echo_stamp "Remove the build scripts"
  rm -rf /root/clover-image

  echo_stamp "End of cleanup" SUCCESS
}

# Sourcing (for tests) defines the functions only
if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
  main "$@"
fi
